### ISSUE TITLE
Problem with ant design

### ISSUE THREAD

**Issue by ghost** [Arelav/react-app-rewire-typescript-hmr#1]
Hi.
I've tried to use react-app-rewire-typescript-hmr with Ant Design. I've installed antd with the ts-import-plugin according to their docs: https://ant.design/docs/react/use-in-typescript
However I cannot seem to get that working with hmr. 
The error I'm getting at the console:

> module.js:471
    throw err;
Error: Cannot find module 'react-hot-loader/webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at module.exports (C:\Users\M013435\WebstormProjects\Adam\parcel-project\node_modules\react-app-rewire-typescript-hmr\index.js:44:29)
    at Object.override [as webpack] (C:\Users\M013435\WebstormProjects\Adam\parcel-project\config-overrides.js:24:10)
    at Object.<anonymous> (C:\Users\M013435\WebstormProjects\Adam\parcel-project\node_modules\react-app-rewired\scripts\start.js:13:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

And the log:
> 0 info it worked if it ends with ok
1 verbose cli [ 'c:\\tools\\nodejs\\6.9.1\\node.exe',
1 verbose cli   'c:\\tools\\nodejs\\6.9.1\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.7.1
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parcel-project@0.1.0~prestart: parcel-project@0.1.0
6 info lifecycle parcel-project@0.1.0~start: parcel-project@0.1.0
7 verbose lifecycle parcel-project@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle parcel-project@0.1.0~start: PATH: c:\tools\nodejs\6.9.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\M013435\WebstormProjects\Adam\parcel-project\node_modules\.bin;C:\tools\cmder\1.3\bin;C:\tools\cmder\1.3\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder\1.3\vendor\conemu-maximus5;C:\tools\cmder\1.3\vendor\conemu-maximus5\ConEmu;C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;;c:/tools\devtool\1.37\bin;c:/tools\git\2.13.2\bin;c:/tools\winpython\2.7.12.4\scripts;c:/tools\curl\7.56.1\bin;c:/tools\maven\3.5.2\bin;c:/tools\jdk\1.8.152.64\bin;;c:/tools\nodejs\6.9.1\.;;c:\tools\git\2.13.2\usr\bin;c:\tools\git\2.13.2\usr\share\vim\vim74;C:\tools\cmder\1.3\
9 verbose lifecycle parcel-project@0.1.0~start: CWD: C:\Users\M013435\WebstormProjects\Adam\parcel-project
10 silly lifecycle parcel-project@0.1.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'react-app-rewired start --scripts-version react-scripts-ts' ]
11 silly lifecycle parcel-project@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle parcel-project@0.1.0~start: Failed to exec start script
13 verbose stack Error: parcel-project@0.1.0 start: `react-app-rewired start --scripts-version react-scripts-ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (c:\tools\nodejs\6.9.1\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (c:\tools\nodejs\6.9.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid parcel-project@0.1.0
15 verbose cwd C:\Users\M013435\WebstormProjects\Adam\parcel-project
16 verbose Windows_NT 6.1.7601
17 verbose argv "c:\\tools\\nodejs\\6.9.1\\node.exe" "c:\\tools\\nodejs\\6.9.1\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.9.1
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error parcel-project@0.1.0 start: `react-app-rewired start --scripts-version react-scripts-ts`
22 error Exit status 1
23 error Failed at the parcel-project@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Arelav** [comment]
Unfortunately, advanced ts-loader tweaking is not implemented.This rewire plugin only adds HMR webpack settings. For now, I stopped using react-rewire but I'll be appreciated to help with this issue. I have not so much time to work on it and if you have a pull request you are welcome.
